class Building:
    def __init__(self, length: int, width: int, height: int, name: str) -> None:
        self.length = length
        self.width = width
        self.height = height

        self.BASE_NAME = name
        self.display_name = name # Can be changed by player

class Fixed:
    """
    Fixed structures which do not get automatically torn down, rebuilt, or
    abandoned.
    """
    def __init__(self, length: int, width: int, height: int, name: str) -> None:
        super().__init__(self, length, width, height)

class Zonable:
    """
    Structures which are generated by the game inside of zones
    """
    def __init__(self, length: int, width: int, height: int, name: str) -> None:
        super().__init__(self, length, width, height)
        self.abandoned = False
